[config]
schemaVersion = "0.0.1"

[package]
namespace = "Galactic_Scale"
name = "GalacticScale"
versionNumber = "2.12.43"
description = "v2.12.43 Galaxy Customization. New Planets. Different Sized Planets. Up to 100 Planets/star and 1024 Stars. DF is more or less balanced. See GS Discord Server"
websiteUrl = "https://github.com/Touhma/DSP_Plugins"
containsNsfwContent = false

[package.dependencies]
"xiaoye97-BepInEx" = "5.4.17"
"crecheng-CloseError" = "1.0.0"

[build]
icon = "./Package/icon.png"
readme = "./Package/README.md"
outdir = "./"

[[build.copy]]
source = "./obj/Debug/net472/GalacticScale.dll"
target = "./GalacticScale.dll"
[[build.copy]]
source = "./Package/GSUI.dll"
target = "./GSUI.dll"
[[build.copy]]
source = "./Package/3rdPartyLicenses.md"
target = "./3rdPartyLicenses.md"
[[build.copy]]
source = "./Package/galacticbundle"
target = "./galacticbundle"
[publish]
repository = "https://dsp.thunderstore.io"
communities = ["dyson-sphere-program"]
categories = []
